# Generated by Django 5.0.6 on 2024-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
